function plot_timing_doppler_2d_sensitivity( ...
    inputFile, outputDir)
% ============================================================
% plot_timing_doppler_2d_sensitivity.m
%
% Official reporting for the joint residual timing-Doppler
% sensitivity analysis.
%
% Two heatmaps are generated:
%
%   1) QPSK,   k=7, N_R=256
%   2) 16-QAM, k=4, N_R=256
%
% Only OBSERVED positive BER values are represented by the
% heatmap color scale.
%
% Zero-error Monte Carlo runs are excluded from the BER color
% map and labelled as "0 err". Their one-sided 95% BER upper
% bound is reported separately.
%
% The nominal operating point is indicated only by a black
% outline around its corresponding cell. No marker or legend
% is placed over the measured values.
%
% Inputs:
%
%   inputFile
%       timing_doppler_2d_sensitivity_results.mat
%
%   outputDir
%       Destination folder for generated figures.
%
% TFG:       Cooperative Waveform Transmission and Design
%            for LEO Satellites
% Author:    Emma Rodriguez Hervas - UC3M
% Year:      2026
% ============================================================

% ------------------------------------------------------------
% 1. Validate inputs
% ------------------------------------------------------------

if nargin ~= 2
    error('plot_timing_doppler_2d_sensitivity:InvalidInputs', ...
        'inputFile and outputDir are required.');
end

if isstring(inputFile)
    inputFile = char(inputFile);
end

if isstring(outputDir)
    outputDir = char(outputDir);
end

if ~isfile(inputFile)
    error('plot_timing_doppler_2d_sensitivity:ResultsNotFound', ...
        'Results file not found:\n%s', ...
        inputFile);
end

if ~isfolder(outputDir)
    mkdir(outputDir);
end

% ------------------------------------------------------------
% 2. Load production results
% ------------------------------------------------------------

S = load( ...
    inputFile, ...
    'results', ...
    'studyMeta');

if ~isfield(S, 'results') || ...
        isempty(S.results)

    error('plot_timing_doppler_2d_sensitivity:EmptyResults', ...
        'The results file contains no valid results.');
end

if ~isfield(S, 'studyMeta')
    error('plot_timing_doppler_2d_sensitivity:MissingMetadata', ...
        'The results file does not contain studyMeta.');
end

results = ...
    S.results;

studyMeta = ...
    S.studyMeta;

if isfield(studyMeta, 'expectedPoints')

    expectedPoints = ...
        studyMeta.expectedPoints;

else

    expectedPoints = 50;
end

if numel(results) ~= expectedPoints
    error('plot_timing_doppler_2d_sensitivity:IncompleteResults', ...
        ['Expected %d timing-Doppler points, ' ...
         'but found %d.'], ...
        expectedPoints, ...
        numel(results));
end

% ------------------------------------------------------------
% 3. Recover study definition
% ------------------------------------------------------------

if isfield(studyMeta, 'deltaValues')

    deltaValues = ...
        studyMeta.deltaValues;

else

    deltaValues = ...
        [-1023 -504 0 504 1023];
end

if isfield(studyMeta, 'nuRelHzValues')

    nuRelHzValues = ...
        studyMeta.nuRelHzValues;

else

    nuRelHzValues = ...
        [-26460 -13230 0 13230 26460];
end

if isfield(studyMeta, 'NR')

    NR = ...
        studyMeta.NR;

else

    NR = 256;
end

if NR ~= 256
    error('plot_timing_doppler_2d_sensitivity:UnexpectedNR', ...
        'Expected N_R=256, got N_R=%d.', ...
        NR);
end

nuRelKHzValues = ...
    nuRelHzValues / 1e3;

nominalDelta = ...
    504;

nominalNuRelHz = ...
    -13.23e3;

% ------------------------------------------------------------
% 4. Modulation definitions
% ------------------------------------------------------------

modulations = struct( ...
    'name', {}, ...
    'fileTag', {});

modulations(1).name = ...
    'QPSK';

modulations(1).fileTag = ...
    'qpsk';

modulations(2).name = ...
    '16-QAM';

modulations(2).fileTag = ...
    '16qam';

% ------------------------------------------------------------
% 5. Reconstruct measured BER matrices
% ------------------------------------------------------------

berMatrices = ...
    cell(1, numel(modulations));

zeroBoundMatrices = ...
    cell(1, numel(modulations));

allMeasuredValues = [];

for modIdx = 1:numel(modulations)

    modulation = ...
        modulations(modIdx).name;

    [berMatrix, zeroBoundMatrix] = ...
        local_build_matrices( ...
            results, ...
            modulation, ...
            deltaValues, ...
            nuRelHzValues);

    berMatrices{modIdx} = ...
        berMatrix;

    zeroBoundMatrices{modIdx} = ...
        zeroBoundMatrix;

    measuredValues = ...
        berMatrix( ...
            isfinite(berMatrix) & ...
            berMatrix > 0);

    allMeasuredValues = [ ...
        allMeasuredValues; ...
        measuredValues(:)]; %#ok<AGROW>
end

if isempty(allMeasuredValues)
    error('plot_timing_doppler_2d_sensitivity:NoMeasuredBER', ...
        ['No observed positive BER values are available ' ...
         'for the heatmap.']);
end

% ------------------------------------------------------------
% 6. Common color limits
% ------------------------------------------------------------

logMeasuredValues = ...
    log10(allMeasuredValues);

globalColorMin = ...
    min(logMeasuredValues);

globalColorMax = ...
    max(logMeasuredValues);

if globalColorMin == globalColorMax

    globalColorMin = ...
        globalColorMin - 0.5;

    globalColorMax = ...
        globalColorMax + 0.5;
end

% Grid-cell edges used to outline the nominal point.
nuEdgesKHz = ...
    local_grid_edges( ...
        nuRelKHzValues);

deltaEdges = ...
    local_grid_edges( ...
        deltaValues);

nominalNuIdx = find( ...
    abs( ...
        nuRelHzValues - ...
        nominalNuRelHz) < 1e-9, ...
    1);

nominalDeltaIdx = find( ...
    deltaValues == nominalDelta, ...
    1);

if isempty(nominalNuIdx) || ...
        isempty(nominalDeltaIdx)

    error('plot_timing_doppler_2d_sensitivity:MissingNominalPoint', ...
        'Nominal timing-Doppler point is not present in the grid.');
end

% ------------------------------------------------------------
% 7. Generate heatmaps
% ------------------------------------------------------------

for modIdx = 1:numel(modulations)

    modulation = ...
        modulations(modIdx).name;

    berMatrix = ...
        berMatrices{modIdx};

    % Zero-error cells remain NaN.
    logBerMatrix = ...
        log10(berMatrix);

    fig = figure( ...
        'Visible', 'on', ...
        'Color', 'w', ...
        'Position', [100 100 900 650]);

    ax = axes(fig);

    imageHandle = imagesc( ...
        ax, ...
        nuRelKHzValues, ...
        deltaValues, ...
        logBerMatrix);

    axis(ax, 'xy');

    % NaN values correspond to zero-error runs and remain
    % transparent rather than being assigned an artificial BER.
    imageHandle.AlphaData = ...
        isfinite(logBerMatrix);

    colormap( ...
        ax, ...
        parula);

    caxis( ...
        ax, ...
        [globalColorMin globalColorMax]);

    cb = ...
        colorbar(ax);

    cb.Label.String = ...
        'log_{10}(observed BER)';

    cb.Label.Interpreter = ...
        'tex';

    hold(ax, 'on');
    box(ax, 'on');

    % --------------------------------------------------------
    % Cell labels
    % --------------------------------------------------------

    for deltaIdx = 1:numel(deltaValues)

        for nuIdx = 1:numel(nuRelKHzValues)

            if isfinite( ...
                    berMatrix(deltaIdx, nuIdx))

                labelText = sprintf( ...
                    '%.1e', ...
                    berMatrix(deltaIdx, nuIdx));

            else

                labelText = ...
                    '0 err';
            end

            text( ...
                ax, ...
                nuRelKHzValues(nuIdx), ...
                deltaValues(deltaIdx), ...
                labelText, ...
                'HorizontalAlignment', 'center', ...
                'VerticalAlignment', 'middle', ...
                'FontSize', 16);
        end
    end

    % --------------------------------------------------------
    % Nominal reference cell
    % --------------------------------------------------------

    nominalX0 = ...
        nuEdgesKHz(nominalNuIdx);

    nominalX1 = ...
        nuEdgesKHz(nominalNuIdx + 1);

    nominalY0 = ...
        deltaEdges(nominalDeltaIdx);

    nominalY1 = ...
        deltaEdges(nominalDeltaIdx + 1);

    rectangle( ...
        ax, ...
        'Position', ...
        [ ...
            nominalX0, ...
            nominalY0, ...
            nominalX1 - nominalX0, ...
            nominalY1 - nominalY0 ...
        ], ...
        'EdgeColor', 'k', ...
        'LineWidth', 2.0);

    % --------------------------------------------------------
    % Axes and title
    % --------------------------------------------------------

    xlabel( ...
        ax, ...
        'Residual Doppler, \nu_{rel} [kHz]');

    ylabel( ...
        ax, ...
        'Residual timing offset, \delta [samples]');

    title( ...
        ax, ...
        sprintf( ...
            '%s - joint timing-Doppler sensitivity, N_R=%d', ...
            modulation, ...
            NR), ...
        'FontWeight', 'normal');


    xticks( ...
        ax, ...
        nuRelKHzValues);

    yticks( ...
        ax, ...
        deltaValues);

    ax.FontSize = 18;

    % --------------------------------------------------------
    % Export
    % --------------------------------------------------------

    baseName = sprintf( ...
        'ber_sensitivity_timing_doppler_2d_%s', ...
        modulations(modIdx).fileTag);

    save_official_figure( ...
        fig, ...
        outputDir, ...
        baseName);

    % Figure intentionally remains open in MATLAB.
end

end


% ============================================================
% Local helpers
% ============================================================

function [berMatrix, zeroBoundMatrix] = ...
    local_build_matrices( ...
        results, modulation, ...
        deltaValues, nuRelHzValues)

numDelta = ...
    numel(deltaValues);

numNu = ...
    numel(nuRelHzValues);

berMatrix = ...
    NaN(numDelta, numNu);

zeroBoundMatrix = ...
    NaN(numDelta, numNu);

requestedModulation = ...
    local_normalize_modulation(modulation);

numMatched = 0;

for idx = 1:numel(results)

    storedModulation = ...
        local_normalize_modulation( ...
            results(idx).modulation);

    if ~strcmp( ...
            storedModulation, ...
            requestedModulation)

        continue;
    end

    deltaIdx = find( ...
        deltaValues == ...
        results(idx).delta, ...
        1);

    nuIdx = find( ...
        abs( ...
            nuRelHzValues - ...
            results(idx).nuRelHz) < 1e-9, ...
        1);

    if isempty(deltaIdx) || ...
            isempty(nuIdx)

        error('plot_timing_doppler_2d_sensitivity:UnexpectedGridPoint', ...
            ['Result contains a timing-Doppler point ' ...
             'outside the expected grid.']);
    end

    if isfinite(berMatrix(deltaIdx, nuIdx)) || ...
            isfinite(zeroBoundMatrix(deltaIdx, nuIdx))

        error('plot_timing_doppler_2d_sensitivity:DuplicateGridPoint', ...
            ['Duplicate result for delta=%g and ' ...
             'nuRelHz=%g.'], ...
            results(idx).delta, ...
            results(idx).nuRelHz);
    end

    [berValue, numErrors, numBits] = ...
        local_get_ber_fields( ...
            results(idx));

    if abs( ...
            berValue - ...
            numErrors / numBits) > 1e-12

        error('plot_timing_doppler_2d_sensitivity:BERMismatch', ...
            'Stored BER does not match numErrors/numBits.');
    end

    if numErrors == 0

        zeroBoundMatrix(deltaIdx, nuIdx) = ...
            local_get_upper_bound( ...
                results(idx));

    else

        berMatrix(deltaIdx, nuIdx) = ...
            berValue;
    end

    numMatched = ...
        numMatched + 1;
end

expectedMatched = ...
    numDelta * numNu;

if numMatched ~= expectedMatched
    error('plot_timing_doppler_2d_sensitivity:MissingGridPoints', ...
        ['Expected %d points for modulation %s, ' ...
         'but found %d.'], ...
        expectedMatched, ...
        modulation, ...
        numMatched);
end

end


function [berValue, numErrors, numBits] = ...
    local_get_ber_fields(row)

if isfield(row, 'BER')

    berValue = ...
        row.BER;

elseif isfield(row, 'BERcomb')

    berValue = ...
        row.BERcomb;

else

    error('plot_timing_doppler_2d_sensitivity:MissingBER', ...
        'Result entry does not contain BER.');
end

if isfield(row, 'numErrors')

    numErrors = ...
        row.numErrors;

elseif isfield(row, 'Ecomb')

    numErrors = ...
        row.Ecomb;

else

    error('plot_timing_doppler_2d_sensitivity:MissingErrors', ...
        'Result entry does not contain an error count.');
end

if isfield(row, 'numBits')

    numBits = ...
        row.numBits;

elseif isfield(row, 'Nbits')

    numBits = ...
        row.Nbits;

else

    error('plot_timing_doppler_2d_sensitivity:MissingBits', ...
        'Result entry does not contain a bit count.');
end

if ~isfinite(numBits) || ...
        numBits <= 0

    error('plot_timing_doppler_2d_sensitivity:InvalidBits', ...
        'Number of evaluated bits must be positive.');
end

end


function upperBound = ...
    local_get_upper_bound(row)

if isfield(row, 'upper95BERcomb') && ...
        isfinite(row.upper95BERcomb) && ...
        row.upper95BERcomb > 0

    upperBound = ...
        row.upper95BERcomb;

    return;
end

[~, ~, numBits] = ...
    local_get_ber_fields(row);

upperBound = ...
    1 - 0.05^(1 / numBits);

end


function edges = ...
    local_grid_edges(values)

values = ...
    values(:).';

if numel(values) < 2
    error('plot_timing_doppler_2d_sensitivity:InvalidGrid', ...
        'At least two grid values are required.');
end

midpoints = ...
    (values(1:end-1) + ...
     values(2:end)) / 2;

firstEdge = ...
    values(1) - ...
    (midpoints(1) - values(1));

lastEdge = ...
    values(end) + ...
    (values(end) - midpoints(end));

edges = ...
    [firstEdge midpoints lastEdge];

end


function normalized = ...
    local_normalize_modulation(value)

value = ...
    upper(regexprep( ...
        char(value), ...
        '[^A-Z0-9]', ...
        ''));

if strcmp(value, 'QPSK')

    normalized = ...
        'QPSK';

elseif strcmp(value, '16QAM') || ...
        strcmp(value, 'QAM16')

    normalized = ...
        '16QAM';

else

    error('plot_timing_doppler_2d_sensitivity:UnknownModulation', ...
        'Unknown modulation label: %s.', ...
        value);
end

end