function plot_load_se_vs_ber( ...
    boostedResults, unboostedResults, ...
    rateResults, outputDir)
% ============================================================
% plot_load_se_vs_ber.m
%
% Official payload-SE versus BER load-tradeoff figures.
%
% Representative operating point:
%
%   N_R = 400
%
% Only positive BER values actually observed in Monte Carlo
% are drawn and connected.
%
% Zero-error cases are NOT represented as positive BER points
% and are NOT connected to measured data. Their conservative
% 95% upper-bound level is shown as a dashed horizontal line.
%
% TFG:       Cooperative Waveform Transmission and Design
%            for LEO Satellites
% Author:    Emma Rodriguez Hervas - UC3M
% Year:      2026
% ============================================================

NRrep = 400;

policies = {'boosted', 'unboosted'};

for polIdx = 1:numel(policies)

    powerPolicy = policies{polIdx};

    if strcmp(powerPolicy, 'boosted')
        results = boostedResults;
    else
        results = unboostedResults;
    end

    fig = figure( ...
        'Visible', 'on', ...
        'Color', 'w', ...
        'Position', [100 100 900 650]);

    ax = axes(fig);

    hold(ax, 'on');
    grid(ax, 'on');
    box(ax, 'on');

    % --------------------------------------------------------
    % QPSK family
    % --------------------------------------------------------

    qpskK = [7 8 9 10];

    [qpskSE, qpskBER, qpskUpper95] = ...
        local_collect_family( ...
            results, ...
            rateResults, ...
            'QPSK', ...
            qpskK, ...
            NRrep);

    qpskMeasuredMask = ...
        isfinite(qpskBER);

    semilogy( ...
        ax, ...
        qpskSE(qpskMeasuredMask), ...
        qpskBER(qpskMeasuredMask), ...
        '-o', ...
        'LineWidth', 1.6, ...
        'MarkerSize', 7, ...
        'DisplayName', 'QPSK');

    % --------------------------------------------------------
    % 16-QAM family
    % --------------------------------------------------------

    qamK = [4 5 6 7 8];

    [qamSE, qamBER, qamUpper95] = ...
        local_collect_family( ...
            results, ...
            rateResults, ...
            '16-QAM', ...
            qamK, ...
            NRrep);

    qamMeasuredMask = ...
        isfinite(qamBER);

    semilogy( ...
        ax, ...
        qamSE(qamMeasuredMask), ...
        qamBER(qamMeasuredMask), ...
        '-s', ...
        'LineWidth', 1.6, ...
        'MarkerSize', 7, ...
        'DisplayName', '16-QAM');

    % --------------------------------------------------------
    % k labels for measured points
    % --------------------------------------------------------

    for idx = find(qpskMeasuredMask)

        text( ...
            ax, ...
            qpskSE(idx), ...
            qpskBER(idx) * 1.4, ...
            sprintf('\\lambda=%d', qpskK(idx)), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'bottom', ...
            'FontSize', 16);
    end

    for idx = find(qamMeasuredMask)

        text( ...
            ax, ...
            qamSE(idx), ...
            qamBER(idx) / 1.4, ...
            sprintf('\\lambda=%d', qamK(idx)), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'top', ...
            'FontSize', 16);
    end

    % --------------------------------------------------------
    % Zero-error reference line
    % --------------------------------------------------------

    allUpper95 = [ ...
        qpskUpper95(isfinite(qpskUpper95)), ...
        qamUpper95(isfinite(qamUpper95))];

    if ~isempty(allUpper95)

        zeroBoundLevel = ...
            max(allUpper95);

        yline( ...
            ax, ...
            zeroBoundLevel, ...
            '--', ...
            'Zero-error 95% upper bound', ...
            'LineWidth', 1.2, ...
            'FontSize', 16, ...
            'LabelHorizontalAlignment', 'right', ...
            'LabelVerticalAlignment', 'top', ...
            'HandleVisibility', 'off');

        % ----------------------------------------------------
        % Label zero-error configurations without plotting a
        % fictitious BER point.
        % ----------------------------------------------------

        % For the boosted policy, the lambda labels of the zero-
        % error points are omitted (they are hard to attribute
        % to a modulation at a glance); the dashed bound line
        % above is kept and explained in the figure caption.
        if ~strcmp(powerPolicy, 'boosted')

            for idx = find(isfinite(qpskUpper95))

                text( ...
                    ax, ...
                    qpskSE(idx), ...
                    zeroBoundLevel * 1.5, ...
                    sprintf('\\lambda=%d (0 errors)', qpskK(idx)), ...
                    'HorizontalAlignment', 'center', ...
                    'VerticalAlignment', 'bottom', ...
                    'FontSize', 16);
            end

            for idx = find(isfinite(qamUpper95))

                text( ...
                    ax, ...
                    qamSE(idx), ...
                    zeroBoundLevel * 2.3, ...
                    sprintf('\\lambda=%d (0 errors)', qamK(idx)), ...
                    'HorizontalAlignment', 'center', ...
                    'VerticalAlignment', 'bottom', ...
                    'FontSize', 16);
            end
        end
    end

    % --------------------------------------------------------
    % Axes
    % --------------------------------------------------------

    ax.YScale = 'log';
    ax.YMinorGrid = 'on';
    ax.FontSize = 18;

    allMeasuredBER = [ ...
        qpskBER(isfinite(qpskBER)), ...
        qamBER(isfinite(qamBER))];

    valuesForLimits = ...
        allMeasuredBER;

    if ~isempty(allUpper95)
        valuesForLimits = [ ...
            valuesForLimits, ...
            max(allUpper95)];
    end

    local_set_log_limits(ax, valuesForLimits);

    allSEValues = [qpskSE, qamSE];
    seRange = max(allSEValues) - min(allSEValues);
    xlim(ax, [min(allSEValues) - 0.08 * seRange, ...
        max(allSEValues) + 0.08 * seRange]);

    xlabel(ax, ...
        'Nominal payload spectral efficiency [bit/s/Hz]');

    ylabel(ax, ...
        sprintf( ...
            'Uncoded combined BER at N_R=%d', ...
            NRrep));

    title(ax, ...
        sprintf( ...
            'Load reliability-SE trade-off - %s', ...
            powerPolicy));

    legend(ax, ...
        'Location', 'northwest');

    baseName = sprintf( ...
        'se_vs_ber_load_%s', ...
        powerPolicy);

    save_official_figure( ...
        fig, outputDir, baseName);

    % Figure intentionally remains open in MATLAB.
end

end


% ============================================================
% Local helpers
% ============================================================

function [seValues, berMeasured, zeroUpper95] = ...
    local_collect_family( ...
        results, rateResults, ...
        modulation, kList, NR)

seValues = zeros(1, numel(kList));
berMeasured = NaN(1, numel(kList));
zeroUpper95 = NaN(1, numel(kList));

for idx = 1:numel(kList)

    k = kList(idx);

    resultMask = ...
        local_modulation_mask(results, modulation) & ...
        [results.k] == k & ...
        [results.NR] == NR;

    if nnz(resultMask) ~= 1
        error('plot_load_se_vs_ber:ResultJoinMismatch', ...
            'Expected one result for %s k=%d NR=%d.', ...
            modulation, k, NR);
    end

    row = results(resultMask);

    if abs(row.BERcomb - ...
            row.Ecomb / row.Nbits) > 1e-12
        error('plot_load_se_vs_ber:BERMismatch', ...
            'Stored BER does not match Ecomb/Nbits.');
    end

    if row.Ecomb == 0

        if isfield(row, 'upper95BERcomb') && ...
                isfinite(row.upper95BERcomb) && ...
                row.upper95BERcomb > 0

            zeroUpper95(idx) = ...
                row.upper95BERcomb;

        else

            zeroUpper95(idx) = ...
                1 - 0.05^(1 / row.Nbits);
        end

    else

        berMeasured(idx) = ...
            row.BERcomb;
    end

    rateMask = ...
        local_modulation_mask(rateResults, modulation) & ...
        [rateResults.k] == k;

    if nnz(rateMask) ~= 1
        error('plot_load_se_vs_ber:RateJoinMismatch', ...
            'Expected one rate result for %s k=%d.', ...
            modulation, k);
    end

    seValues(idx) = ...
        rateResults(rateMask).payloadSE;
end

end


function local_set_log_limits(ax, values)

values = values(isfinite(values) & values > 0);

if isempty(values)
    error('plot_load_se_vs_ber:NoPositiveValues', ...
        'No positive values available for logarithmic axis.');
end

yMin = ...
    10 ^ floor(log10(min(values)));

yMax = ...
    10 ^ ceil(log10(max(values) * 1.2));

yMax = min(1, yMax);

if yMax <= yMin
    yMax = min(1, 10 * yMin);
end

ylim(ax, [yMin, yMax]);

end


function mask = local_modulation_mask(results, requested)

mask = false(size(results));

requested = ...
    local_normalize_modulation(requested);

for idx = 1:numel(results)

    stored = ...
        local_normalize_modulation( ...
            results(idx).modulation);

    mask(idx) = ...
        strcmp(stored, requested);
end

end


function normalized = local_normalize_modulation(value)

value = ...
    upper(regexprep( ...
        char(value), ...
        '[^A-Z0-9]', ...
        ''));

if strcmp(value, 'QPSK')

    normalized = 'QPSK';

elseif strcmp(value, '16QAM') || ...
        strcmp(value, 'QAM16')

    normalized = '16QAM';

else

    error('plot_load_se_vs_ber:UnknownModulation', ...
        'Unknown modulation label: %s.', value);
end

end