function summary = ...
    validate_official_no_compensation_vs_reference()
% ============================================================
% validate_official_no_compensation_vs_reference.m
%
% Regression validation for the official B3
% no-compensation ablation.
%
% Three properties are checked:
%
% A. PHYSICAL-CONFIGURATION MATCH
%    Baseline and no-compensation use the same physical and
%    Monte Carlo parameters. The intended difference is the
%    satellite-2 TX compensation toggle.
%
% B. COMPENSATED EQUIVALENCE
%    With applyPrecoder=true, run_no_compensation_point.m must
%    reproduce the official baseline Monte Carlo counts
%    exactly for the same operating point.
%
% C. PAIRED ABLATION SANITY CHECK
%    With applyPrecoder=false:
%
%      - the same resolved Monte Carlo seed is used;
%      - the receiver processing remains unchanged;
%      - the BER is worse than the compensated baseline for
%        the selected deterministic validation cases.
%
% The last condition is a sanity check for these fixed test
% cases, not a general mathematical requirement for every
% possible short Monte Carlo realization.
%
% TFG:       Cooperative Waveform Transmission and Design
%            for LEO Satellites
% Author:    Emma Rodriguez Hervas - UC3M
% Year:      2026
% ============================================================

% ------------------------------------------------------------
% 1. Project setup
% ------------------------------------------------------------

thisFolder = ...
    fileparts(mfilename('fullpath'));

projectRoot = ...
    thisFolder;

while ~isfolder( ...
        fullfile(projectRoot, 'pipeline'))

    parentFolder = ...
        fileparts(projectRoot);

    if strcmp(parentFolder, projectRoot)

        error( ...
            ['validate_official_no_compensation_vs_reference:' ...
             'ProjectRootNotFound'], ...
            'Could not locate the project root.');
    end

    projectRoot = ...
        parentFolder;
end

addpath(genpath(projectRoot));

fprintf('============================================================\n');
fprintf('OFFICIAL NO-COMPENSATION VALIDATION\n');
fprintf('============================================================\n\n');

% ------------------------------------------------------------
% 2. Deterministic short validation cases
% ------------------------------------------------------------

testCases = struct( ...
    'modulation', {'QPSK', '16-QAM'}, ...
    'NR', {144, 256});

seedShort = 1;
minErrorsShort = 15;
maxBitsShort = 1000000;

summary = repmat(struct( ...
    'modulation', '', ...
    'NR', NaN, ...
    'configMatchPass', false, ...
    'equivalencePass', false, ...
    'pairedSeedPass', false, ...
    'baselineCounts', [], ...
    'equivalentCounts', [], ...
    'resolvedSeed', NaN, ...
    'baselineBER', NaN, ...
    'ablationBER', NaN, ...
    'ablationWorsePass', false, ...
    'pass', false), ...
    1, ...
    numel(testCases));

% ------------------------------------------------------------
% 3. Execute validation cases
% ------------------------------------------------------------

for tc = 1:numel(testCases)

    modulation = ...
        testCases(tc).modulation;

    NR = ...
        testCases(tc).NR;

    fprintf('------------------------------------------------------------\n');
    fprintf('%s, NR=%d\n', modulation, NR);
    fprintf('------------------------------------------------------------\n');

    % --------------------------------------------------------
    % A. Official compensated baseline
    % --------------------------------------------------------

    cfgBase = ...
        build_official_config( ...
            'baseline', ...
            modulation, ...
            NaN, ...
            'not_applicable', ...
            NR, ...
            'Seed', seedShort, ...
            'TargetErrors', minErrorsShort, ...
            'MaxBits', maxBitsShort);

    resBase = ...
        run_baseline_point(cfgBase);

    % --------------------------------------------------------
    % B. Same B3 engine with compensation enabled
    % --------------------------------------------------------

    cfgEquiv = ...
        build_official_config( ...
            'no_compensation', ...
            modulation, ...
            NaN, ...
            'not_applicable', ...
            NR, ...
            'Seed', seedShort, ...
            'TargetErrors', minErrorsShort, ...
            'MaxBits', maxBitsShort, ...
            'ApplyPrecoder', true);

    resEquiv = ...
        run_no_compensation_point(cfgEquiv);

    % --------------------------------------------------------
    % C. Actual B3 ablation
    % --------------------------------------------------------

    cfgAbl = ...
        build_official_config( ...
            'no_compensation', ...
            modulation, ...
            NaN, ...
            'not_applicable', ...
            NR, ...
            'Seed', seedShort, ...
            'TargetErrors', minErrorsShort, ...
            'MaxBits', maxBitsShort, ...
            'ApplyPrecoder', false);

    resAbl = ...
        run_no_compensation_point(cfgAbl);

    % --------------------------------------------------------
    % 3.1 Physical-configuration regression
    % --------------------------------------------------------

    configMatchPass = ...
        local_same_physical_configuration( ...
            cfgBase, ...
            cfgAbl);

    % --------------------------------------------------------
    % 3.2 Compensated-engine equivalence
    % --------------------------------------------------------

    baselineCounts = [ ...
        resBase.numErrors, ...
        resBase.numBits, ...
        resBase.runtimeMetadata.numRealizations];

    equivalentCounts = [ ...
        resEquiv.numErrors, ...
        resEquiv.numBits, ...
        resEquiv.runtimeMetadata.numRealizations];

    equivalencePass = ...
        isequal( ...
            baselineCounts, ...
            equivalentCounts) && ...
        isequaln( ...
            resBase.BER, ...
            resEquiv.BER);

    % --------------------------------------------------------
    % 3.3 Paired Monte Carlo seed
    % --------------------------------------------------------

    resolvedSeedBase = ...
        local_resolved_seed(cfgBase);

    resolvedSeedEquiv = ...
        local_resolved_seed(cfgEquiv);

    resolvedSeedAbl = ...
        local_resolved_seed(cfgAbl);

    pairedSeedPass = ...
        resolvedSeedBase == resolvedSeedEquiv && ...
        resolvedSeedBase == resolvedSeedAbl;

    % --------------------------------------------------------
    % 3.4 Fixed-case ablation sanity check
    % --------------------------------------------------------

    ablationWorsePass = ...
        resAbl.BER > resBase.BER;

    % --------------------------------------------------------
    % 3.5 Case verdict
    % --------------------------------------------------------

    pass = ...
        configMatchPass && ...
        equivalencePass && ...
        pairedSeedPass && ...
        ablationWorsePass;

    summary(tc).modulation = ...
        modulation;

    summary(tc).NR = ...
        NR;

    summary(tc).configMatchPass = ...
        configMatchPass;

    summary(tc).equivalencePass = ...
        equivalencePass;

    summary(tc).pairedSeedPass = ...
        pairedSeedPass;

    summary(tc).baselineCounts = ...
        baselineCounts;

    summary(tc).equivalentCounts = ...
        equivalentCounts;

    summary(tc).resolvedSeed = ...
        resolvedSeedBase;

    summary(tc).baselineBER = ...
        resBase.BER;

    summary(tc).ablationBER = ...
        resAbl.BER;

    summary(tc).ablationWorsePass = ...
        ablationWorsePass;

    summary(tc).pass = ...
        pass;

    % --------------------------------------------------------
    % 3.6 Console report
    % --------------------------------------------------------

    fprintf('Physical configuration : %s\n', ...
        local_pass_label(configMatchPass));

    fprintf('Compensated equivalence: %s\n', ...
        local_pass_label(equivalencePass));

    fprintf('Paired Monte Carlo seed: %s\n', ...
        local_pass_label(pairedSeedPass));

    fprintf('Resolved seed           : %.0f\n', ...
        resolvedSeedBase);

    fprintf('Baseline BER            : %.6e\n', ...
        resBase.BER);

    fprintf('No-compensation BER     : %.6e\n', ...
        resAbl.BER);

    fprintf('Ablation sanity check   : %s\n', ...
        local_pass_label(ablationWorsePass));

    fprintf('Case verdict             : %s\n\n', ...
        local_pass_label(pass));
end

% ------------------------------------------------------------
% 4. Overall verdict
% ------------------------------------------------------------

allPass = ...
    all([summary.pass]);

fprintf('============================================================\n');
fprintf('FINAL B3 VALIDATION VERDICT\n');
fprintf('============================================================\n');

fprintf('Overall: %s\n', ...
    local_pass_label(allPass));

% ------------------------------------------------------------
% 5. Save evidence
% ------------------------------------------------------------

resultsFolder = ...
    fullfile( ...
        projectRoot, ...
        'results');

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

evidenceFile = ...
    fullfile( ...
        resultsFolder, ...
        'validate_official_no_compensation_vs_reference.mat');

save( ...
    evidenceFile, ...
    'summary', ...
    'allPass');

fprintf('Evidence saved: %s\n', evidenceFile);

if ~allPass

    error( ...
        ['validate_official_no_compensation_vs_reference:' ...
         'ValidationFailed'], ...
        'One or more official B3 validation checks failed.');
end

end


% ============================================================
% Local helpers
% ============================================================

function tf = ...
    local_same_physical_configuration(cfgA, cfgB)

% ------------------------------------------------------------
% Compare parameters that must remain unchanged between the
% compensated baseline and the no-compensation ablation.
% ------------------------------------------------------------

numericFields = { ...
    'M', ...
    'N', ...
    'cpLength', ...
    'iEff', ...
    'kEff', ...
    'kappaEff', ...
    'Ts', ...
    'physicalSamples', ...
    'NR', ...
    'seed', ...
    'targetErrors', ...
    'maxBits'};

tf = true;

for idx = 1:numel(numericFields)

    fieldName = ...
        numericFields{idx};

    if ~isfield(cfgA, fieldName) || ...
            ~isfield(cfgB, fieldName)

        tf = false;
        return;
    end

    if ~isequaln( ...
            cfgA.(fieldName), ...
            cfgB.(fieldName))

        tf = false;
        return;
    end
end

tf = ...
    tf && ...
    strcmp(cfgA.modulation, cfgB.modulation) && ...
    isequaln(cfgA.slantRange, cfgB.slantRange) && ...
    isequaln(cfgA.linkParams, cfgB.linkParams);

% The same validated precoder must be available in both
% configurations even though B3 deliberately does not apply it.
if isfield(cfgA, 'precoderBlocks') && ...
        isfield(cfgB, 'precoderBlocks')

    tf = ...
        tf && ...
        isequaln( ...
            cfgA.precoderBlocks, ...
            cfgB.precoderBlocks);
end

end


function resolvedSeed = ...
    local_resolved_seed(config)

% ------------------------------------------------------------
% Reconstruct the frozen isolated-point seed definition used by
% the official same-grid engines.
% ------------------------------------------------------------

modSeedCode = ...
    baseline_modulation_seed_code( ...
        config.modulation);

nrSeedCode = ...
    nr_seed_code( ...
        config.NR);

resolvedSeed = ...
    config.seed * 1e7 + ...
    modSeedCode * 1e6 + ...
    nrSeedCode * 1e4;

end


function label = ...
    local_pass_label(pass)

if pass
    label = 'PASS';
else
    label = 'FAIL';
end

end