function summary = validate_official_proposal_vs_reference()
% ============================================================
% validate_official_proposal_vs_reference.m
%
% Fast regression of the official heterogeneous-grid proposal.
%
% Validation has two independent layers:
%
%   A. Frozen mapper catalog vs validated experimental source
%   B. Official physical engine vs reference flow
%
% Both physical flows intentionally reuse the same validated
% low-level physical helpers. The regression therefore checks
% the official assembly, configuration, mapper promotion,
% seed convention, stopping logic and BER counters without
% reimplementing already validated physical functions.
%
% No full 20-million-bit Monte Carlo is required.
%
% TFG:       Cooperative Waveform Transmission and Design
%            for LEO Satellites
% Author:    Emma Rodriguez Hervas - UC3M
% Year:      2026
% ============================================================

% ------------------------------------------------------------
% 1. Project setup
% ------------------------------------------------------------

thisFolder = fileparts(mfilename('fullpath'));
projectRoot = thisFolder;

while ~isfolder(fullfile(projectRoot, 'pipeline'))

    parentFolder = fileparts(projectRoot);

    if strcmp(parentFolder, projectRoot)
        error( ...
            'validate_official_proposal_vs_reference:' + ...
            "ProjectRootNotFound", ...
            'Could not locate the project root.');
    end

    projectRoot = parentFolder;
end

addpath(genpath(projectRoot));

% ------------------------------------------------------------
% 2. Load validated experimental candidates
% ------------------------------------------------------------

candidateFile = fullfile( ...
    projectRoot, ...
    'archive', ...
    'load_tradeoff', ...
    'load_tradeoff_candidates.mat');

if ~isfile(candidateFile)
    error('validate_official_proposal_vs_reference:MissingCandidates', ...
        'Missing validated candidate file:\n  %s', candidateFile);
end

S = load(candidateFile, 'candidates');

candidatesRef = S.candidates;

% ============================================================
% A. FROZEN MAPPER REGRESSION
% ============================================================

fprintf('============================================================\n');
fprintf('A. FROZEN MAPPER REGRESSION\n');
fprintf('============================================================\n');

mapperMods = { ...
    'QPSK', 'QPSK', 'QPSK', 'QPSK', ...
    '16-QAM', '16-QAM', '16-QAM', '16-QAM', '16-QAM'};

mapperK = [ ...
    7, 8, 9, 10, ...
    4, 5, 6, 7, 8];

mapperSummary = repmat(struct( ...
    'modulation', '', ...
    'k', NaN, ...
    'pass', false), ...
    1, numel(mapperK));

for idx = 1:numel(mapperK)

    modulation = mapperMods{idx};
    k = mapperK(idx);

    refIdx = find( ...
        strcmp({candidatesRef.modulation}, modulation) & ...
        [candidatesRef.k] == k);

    if numel(refIdx) ~= 1
        error( ...
            'validate_official_proposal_vs_reference:' + ...
            "ReferenceMapperMismatch", ...
            'Expected one reference mapper for %s k=%d.', ...
            modulation, k);
    end

    mapperRef = candidatesRef(refIdx).mapper;
    mapperOff = get_mapper_config(modulation, k);

    pass = local_mapper_core_equal( ...
        mapperRef, ...
        mapperOff);

    mapperSummary(idx).modulation = modulation;
    mapperSummary(idx).k = k;
    mapperSummary(idx).pass = pass;

    fprintf('%-7s k=%-2d : %s\n', ...
        modulation, ...
        k, ...
        local_pass_label(pass));
end

mapperPass = all([mapperSummary.pass]);

fprintf('Mapper catalog: %s\n\n', ...
    local_pass_label(mapperPass));

% ============================================================
% B. PHYSICAL FLOW REGRESSION
% ============================================================

fprintf('============================================================\n');
fprintf('B. PHYSICAL FLOW REGRESSION\n');
fprintf('============================================================\n');

% ------------------------------------------------------------
% 3. Fast physical test cases
% ------------------------------------------------------------

testCases = struct( ...
    'modulation', { ...
        'QPSK', ...
        'QPSK', ...
        '16-QAM', ...
        '16-QAM', ...
        'QPSK'}, ...
    'k', { ...
        7, ...
        8, ...
        4, ...
        7, ...
        7}, ...
    'powerPolicy', { ...
        'boosted', ...
        'boosted', ...
        'boosted', ...
        'boosted', ...
        'unboosted'}, ...
    'NR', { ...
        256, ...
        256, ...
        256, ...
        256, ...
        256});

minErrorsShort = 5;
maxBitsShort = 500000;

% ------------------------------------------------------------
% 4. Independent reference-flow setup
% ------------------------------------------------------------

scenarioRef = channel_scenario();
simParamsRef = simulation_parameters('baseline');
berParamsRef = reference_ber_parameters();

linkParamsRef = struct();

linkParamsRef.speedOfLight = ...
    scenarioRef.constants.speedOfLight;

linkParamsRef.boltzmann = ...
    scenarioRef.constants.boltzmann;

linkParamsRef.carrierFrequency = ...
    scenarioRef.carrierFrequency;

linkParamsRef.eirpDbm = ...
    scenarioRef.eirpDbm;

linkParamsRef.systemTemperature = ...
    scenarioRef.systemTemperature;

linkParamsRef.rxElementGainDb = ...
    scenarioRef.rxElementGainDb;

linkParamsRef.bandwidth = ...
    simParamsRef.bandwidth;

cfgRef = ...
    nominal_proposal_config_1024_16_64();

physicalRef = ...
    nominal_block_framing_16_64(cfgRef);

blockLenRef = ...
    physicalRef.blockLengthSat1;

TsRef = ...
    cfgRef.sampleTime;

NcommonRef = ...
    cfgRef.Ncommon;

deltaRef = 504;
nuRelHzRef = -13.23e3;

nSideRef = ...
    required_side_blocks( ...
        [0 deltaRef], ...
        blockLenRef);

numBlocksMainRef = ...
    2 * nSideRef + 1;

centerIdxMainRef = ...
    nSideRef + 1;

slantRangeRef = [ ...
    scenarioRef.satellites(1).slantRange, ...
    scenarioRef.satellites(2).slantRange];

supportedNRRef = [64 144 256 400];

randomSeedRef = ...
    berParamsRef.randomSeed;

% ------------------------------------------------------------
% 5. Run reference and official flows
% ------------------------------------------------------------

summary = repmat(struct( ...
    'modulation', '', ...
    'k', NaN, ...
    'powerPolicy', '', ...
    'NR', NaN, ...
    'seedCodePass', false, ...
    'refCounts', [], ...
    'officialCounts', [], ...
    'pass', false), ...
    1, numel(testCases));

for tc = 1:numel(testCases)

    modulation = ...
        testCases(tc).modulation;

    k = ...
        testCases(tc).k;

    powerPolicy = ...
        testCases(tc).powerPolicy;

    NR = ...
        testCases(tc).NR;

    % --------------------------------------------------------
    % Reference mapper
    % --------------------------------------------------------

    candIdx = find( ...
        strcmp({candidatesRef.modulation}, modulation) & ...
        [candidatesRef.k] == k);

    if numel(candIdx) ~= 1
        error( ...
            'validate_official_proposal_vs_reference:' + ...
            "CandidateMismatch", ...
            'Expected one reference candidate for %s k=%d.', ...
            modulation, k);
    end

    mapperRef = ...
        candidatesRef(candIdx).mapper;

    nrSeedCodeRef = ...
        find(supportedNRRef == NR, 1);

    candidateSeedCodeRef = ...
        local_reference_candidate_seed_code( ...
            modulation, ...
            k);

    candidateSeedCodeOff = ...
        candidate_seed_code( ...
            modulation, ...
            k);

    seedCodePass = ...
        candidateSeedCodeRef == candidateSeedCodeOff;

    % --------------------------------------------------------
    % Power policy
    % --------------------------------------------------------

    activePerRowRef = 2 * k;

    switch powerPolicy

        case 'boosted'
            ARef = ...
                sqrt(NcommonRef / activePerRowRef);

        case 'unboosted'
            ARef = 1;

        otherwise
            error( ...
                'validate_official_proposal_vs_reference:' + ...
                "InvalidPowerPolicy", ...
                'Unknown power policy.');
    end

    % --------------------------------------------------------
    % Modulation
    % --------------------------------------------------------

    if strcmp(modulation, 'QPSK')

        qamParamsRef = struct( ...
            'modOrder', 4, ...
            'bitsPerSymbol', 2);

    else

        qamParamsRef = struct( ...
            'modOrder', 16, ...
            'bitsPerSymbol', 4);
    end

    % --------------------------------------------------------
    % Mapper indices
    % --------------------------------------------------------

    [sat1IdxRef, sat2IdxRef] = ...
        build_mapper_resource_indices( ...
            mapperRef, ...
            cfgRef.M, ...
            cfgRef.N1, ...
            cfgRef.activeRows);

    sat1IdxRef = sat1IdxRef(:);
    sat2IdxRef = sat2IdxRef(:);

    blockSizeSat1Ref = ...
        cfgRef.K1 * cfgRef.M * cfgRef.N1;

    blockSizeSat2Ref = ...
        cfgRef.M * cfgRef.N2;

    % --------------------------------------------------------
    % Link budget
    % --------------------------------------------------------

    gamma1Ref = compute_link_snr( ...
        NR, ...
        slantRangeRef(1), ...
        linkParamsRef);

    gamma2Ref = compute_link_snr( ...
        NR, ...
        slantRangeRef(2), ...
        linkParamsRef);

    g1Ref = sqrt(gamma1Ref);

    % --------------------------------------------------------
    % Reference Monte Carlo
    % --------------------------------------------------------

    E1r = 0;
    E2r = 0;
    Ecombr = 0;
    Nbitsr = 0;
    rr = 0;

    dopplerInitRef = false;

    dSrcRef = [];
    dSat2AtRxConjRef = [];

    while true

        rr = rr + 1;

        seedRef = ...
            randomSeedRef * 1e7 + ...
            candidateSeedCodeRef * 1e6 + ...
            nrSeedCodeRef * 1e4 + ...
            rr;

        rng(seedRef, 'twister');

        payloads = ...
            generate_common_block_payloads( ...
                numBlocksMainRef, ...
                sat1IdxRef, ...
                sat2IdxRef, ...
                blockSizeSat1Ref, ...
                blockSizeSat2Ref, ...
                qamParamsRef);

        txBitsCenter = ...
            payloads.txBits{centerIdxMainRef};

        txBitsCenter = ...
            txBitsCenter(:);

        phiRel = ...
            2 * pi * rand();

        g2Ref = ...
            sqrt(gamma2Ref) * exp(1j * phiRel);

        dSat1Scaled = ...
            payloads.dSat1Blocks;

        dSat2Scaled = ...
            payloads.dSat2Blocks;

        for blockIdx = 1:numBlocksMainRef

            dSat1Scaled{blockIdx} = ...
                scale_active_symbols( ...
                    payloads.dSat1Blocks{blockIdx}, ...
                    sat1IdxRef, ...
                    ARef);

            dSat2Scaled{blockIdx} = ...
                scale_active_symbols( ...
                    payloads.dSat2Blocks{blockIdx}, ...
                    sat2IdxRef, ...
                    ARef);
        end

        stream = ...
            build_and_combine_streams( ...
                dSat1Scaled, ...
                dSat2Scaled, ...
                cfgRef, ...
                deltaRef);

        streamLen = ...
            numel(stream.s1Stream);

        if ~dopplerInitRef

            m = ...
                (0:streamLen-1).' - ...
                (stream.centerBlockIndex - 1) * blockLenRef;

            dSrcRef = exp( ...
                1j * 2 * pi * ...
                nuRelHzRef * m * TsRef);

            dSat2AtRxConjRef = conj(exp( ...
                1j * 2 * pi * ...
                nuRelHzRef * ...
                (m - deltaRef) * TsRef));

            dopplerInitRef = true;
        end

        s1Channel = ...
            g1Ref .* stream.s1Stream;

        s2Channel = ...
            g2Ref .* dSrcRef .* stream.s2Stream;

        combined = ...
            linear_shift_combine( ...
                s1Channel, ...
                s2Channel, ...
                deltaRef);

        yRx1Clean = ...
            combined.y;

        w = ...
            (randn(streamLen, 1) + ...
             1j * randn(streamLen, 1)) / sqrt(2);

        yRx1Noisy = ...
            yRx1Clean + w;

        yRx2Noisy = ...
            dSat2AtRxConjRef .* yRx1Noisy;

        xrec1 = ...
            r1_sat1_demodulate_block( ...
                yRx1Noisy(stream.rx1Window), ...
                cfgRef.M, ...
                cfgRef.N1, ...
                cfgRef.Lcp);

        xrec2 = ...
            r2_sat2_demodulate_block( ...
                yRx2Noisy(stream.rx2Window), ...
                cfgRef.M, ...
                cfgRef.N2, ...
                cfgRef.Lcp);

        rxSym1 = ...
            xrec1(sat1IdxRef);

        rxSym2 = ...
            xrec2(sat2IdxRef);

        d1 = ...
            rxSym1 / (g1Ref * ARef);

        d2 = ...
            rxSym2 / (g2Ref * ARef);

        dHat = ...
            combine_snr_weighted( ...
                d1, ...
                d2, ...
                gamma1Ref, ...
                gamma2Ref);

        rxBits1 = ...
            demodulate_symbols( ...
                d1, ...
                qamParamsRef);

        rxBits2 = ...
            demodulate_symbols( ...
                d2, ...
                qamParamsRef);

        rxBitsComb = ...
            demodulate_symbols( ...
                dHat, ...
                qamParamsRef);

        rxBits1 = rxBits1(:);
        rxBits2 = rxBits2(:);
        rxBitsComb = rxBitsComb(:);

        [bitErr1, ~] = ...
            compute_ber( ...
                txBitsCenter, ...
                rxBits1);

        [bitErr2, ~] = ...
            compute_ber( ...
                txBitsCenter, ...
                rxBits2);

        [bitErrComb, bitsCmpComb] = ...
            compute_ber( ...
                txBitsCenter, ...
                rxBitsComb);

        E1r = E1r + bitErr1;
        E2r = E2r + bitErr2;
        Ecombr = Ecombr + bitErrComb;

        Nbitsr = ...
            Nbitsr + bitsCmpComb;

        enoughErrors = ...
            E1r >= minErrorsShort && ...
            E2r >= minErrorsShort && ...
            Ecombr >= minErrorsShort;

        if enoughErrors || ...
                Nbitsr >= maxBitsShort
            break;
        end
    end

    % --------------------------------------------------------
    % Official engine
    % --------------------------------------------------------

    configOff = ...
        build_official_config( ...
            'proposal', ...
            modulation, ...
            k, ...
            powerPolicy, ...
            NR, ...
            'Seed', randomSeedRef, ...
            'TargetErrors', minErrorsShort, ...
            'MaxBits', maxBitsShort);

    resultOff = ...
        run_proposal_point(configOff);

    % --------------------------------------------------------
    % Compare exact counters
    % --------------------------------------------------------

    refCounts = [ ...
        E1r, ...
        E2r, ...
        Ecombr, ...
        Nbitsr, ...
        rr];

    officialCounts = [ ...
        resultOff.runtimeMetadata.E1, ...
        resultOff.runtimeMetadata.E2, ...
        resultOff.numErrors, ...
        resultOff.numBits, ...
        resultOff.runtimeMetadata.numRealizations];

    countsPass = ...
        isequal(refCounts, officialCounts);

    pass = ...
        seedCodePass && countsPass;

    summary(tc).modulation = modulation;
    summary(tc).k = k;
    summary(tc).powerPolicy = powerPolicy;
    summary(tc).NR = NR;

    summary(tc).seedCodePass = seedCodePass;

    summary(tc).refCounts = refCounts;
    summary(tc).officialCounts = officialCounts;

    summary(tc).pass = pass;

    fprintf( ...
        '%-7s k=%-2d %-10s NR=%-3d : %s\n', ...
        modulation, ...
        k, ...
        powerPolicy, ...
        NR, ...
        local_pass_label(pass));
end

% ------------------------------------------------------------
% 6. Overall verdict
% ------------------------------------------------------------

physicalPass = ...
    all([summary.pass]);

allPass = ...
    mapperPass && physicalPass;

fprintf('\n');
fprintf('Mapper regression : %s\n', ...
    local_pass_label(mapperPass));

fprintf('Physical regression: %s\n', ...
    local_pass_label(physicalPass));

fprintf('OVERALL            : %s\n', ...
    local_pass_label(allPass));

% ------------------------------------------------------------
% 7. Save evidence
% ------------------------------------------------------------

resultsFolder = fullfile( ...
    projectRoot, ...
    'results');

if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

evidenceFile = fullfile( ...
    resultsFolder, ...
    'validate_official_proposal_vs_reference.mat');

save(evidenceFile, ...
    'summary', ...
    'mapperSummary', ...
    'mapperPass', ...
    'physicalPass', ...
    'allPass', ...
    'minErrorsShort', ...
    'maxBitsShort');

fprintf('Evidence saved: %s\n', evidenceFile);

end


% ============================================================
% Local helpers
% ============================================================

function code = local_reference_candidate_seed_code( ...
    modulation, k)
% Historical mapping copied independently from the validated
% load-tradeoff reference engine.

if strcmp(modulation, 'QPSK')

    if k == 7
        code = 1;

    elseif k == 8
        code = 2;

    elseif k >= 9 && k <= 16
        code = 7 + (k - 8);

    else
        error( ...
            'validate_official_proposal_vs_reference:' + ...
            "InvalidReferenceQpskK", ...
            'Unsupported reference QPSK k=%d.', k);
    end

    return;
end

if strcmp(modulation, '16-QAM')

    if k >= 4 && k <= 8
        code = k - 1;

    elseif k >= 9 && k <= 16
        code = 15 + (k - 8);

    else
        error( ...
            'validate_official_proposal_vs_reference:' + ...
            "InvalidReferenceQamK", ...
            'Unsupported reference 16-QAM k=%d.', k);
    end

    return;
end

error( ...
    'validate_official_proposal_vs_reference:' + ...
    "InvalidReferenceModulation", ...
    'Unknown reference modulation.');

end


function pass = local_mapper_core_equal( ...
    mapperRef, mapperOff)

fields = { ...
    'M', ...
    'N1', ...
    'N2', ...
    'binRow', ...
    'cpLength', ...
    'k', ...
    'componentIds', ...
    'assignment', ...
    'sat1Frames', ...
    'sat1Bins', ...
    'sat2Frames', ...
    'sat2Bins', ...
    'rowUtilizationPct'};

pass = true;

for idx = 1:numel(fields)

    fieldName = fields{idx};

    if ~isfield(mapperRef, fieldName) || ...
            ~isfield(mapperOff, fieldName)

        pass = false;
        return;
    end

    if ~isequaln( ...
            mapperRef.(fieldName), ...
            mapperOff.(fieldName))

        pass = false;
        return;
    end
end

end


function label = local_pass_label(pass)

if pass
    label = 'PASS';
else
    label = 'FAIL';
end

end